export const USERS = [
  {
    value: "john_doe",
    label: "John Doe",
    email: "john.doe@example.com",
    avatar: "https://i.pravatar.cc/150?u=john_doe",
  },
  {
    value: "jane_smith",
    label: "Jane Smith",
    email: "jane.smith@example.com",
    avatar: "https://i.pravatar.cc/150?u=jane_smith",
  },
  {
    value: "bob_jones",
    label: "Bob Jones",
    email: "bob.jones@example.com",
    avatar: "https://i.pravatar.cc/150?u=bob_jones",
  },
  {
    value: "alice_wonderland",
    label: "Alice Wonderland",
    email: "alice.wonderland@example.com",
    avatar: "https://i.pravatar.cc/150?u=alice_wonderland",
  },
  {
    value: "charlie_brown",
    label: "Charlie Brown",
    email: "charlie.brown@example.com",
    avatar: "https://i.pravatar.cc/150?u=charlie_brown",
  },
  {
    value: "emma_stone",
    label: "Emma Stone",
    email: "emma.stone@example.com",
    avatar: "https://i.pravatar.cc/150?u=emma_stone",
  },
  {
    value: "frank_miller",
    label: "Frank Miller",
    email: "frank.miller@example.com",
    avatar: "https://i.pravatar.cc/150?u=frank_miller",
  },
  {
    value: "grace_kelly",
    label: "Grace Kelly",
    email: "grace.kelly@example.com",
    avatar: "https://i.pravatar.cc/150?u=grace_kelly",
  },
  {
    value: "henry_ford",
    label: "Henry Ford",
    email: "henry.ford@example.com",
    avatar: "https://i.pravatar.cc/150?u=henry_ford",
  },
  {
    value: "isabel_garcia",
    label: "Isabel Garcia",
    email: "isabel.garcia@example.com",
    avatar: "https://i.pravatar.cc/150?u=isabel_garcia",
  },
  {
    value: "jack_jackson",
    label: "Jack Jackson",
    email: "jack.jackson@example.com",
    avatar: "https://i.pravatar.cc/150?u=jack_jackson",
  },
  {
    value: "kate_middleton",
    label: "Kate Middleton",
    email: "kate.middleton@example.com",
    avatar: "https://i.pravatar.cc/150?u=kate_middleton",
  },
  {
    value: "leo_dicaprio",
    label: "Leo DiCaprio",
    email: "leo.dicaprio@example.com",
    avatar: "https://i.pravatar.cc/150?u=leo_dicaprio",
  },
  {
    value: "marie_curie",
    label: "Marie Curie",
    email: "marie.curie@example.com",
    avatar: "https://i.pravatar.cc/150?u=marie_curie",
  },
  {
    value: "nathan_davis",
    label: "Nathan Davis",
    email: "nathan.davis@example.com",
    avatar: "https://i.pravatar.cc/150?u=nathan_davis",
  },
  {
    value: "olivia_pope",
    label: "Olivia Pope",
    email: "olivia.pope@example.com",
    avatar: "https://i.pravatar.cc/150?u=olivia_pope",
  },
  {
    value: "peter_parker",
    label: "Peter Parker",
    email: "peter.parker@example.com",
    avatar: "https://i.pravatar.cc/150?u=peter_parker",
  },
  {
    value: "quinn_roberts",
    label: "Quinn Roberts",
    email: "quinn.roberts@example.com",
    avatar: "https://i.pravatar.cc/150?u=quinn_roberts",
  },
  {
    value: "rachel_green",
    label: "Rachel Green",
    email: "rachel.green@example.com",
    avatar: "https://i.pravatar.cc/150?u=rachel_green",
  },
  {
    value: "samuel_jackson",
    label: "Samuel Jackson",
    email: "samuel.jackson@example.com",
    avatar: "https://i.pravatar.cc/150?u=samuel_jackson",
  },
];
